load: POSTWORLD
main: com.datasiqn.arcadia.Arcadia
name: Arcadia
version: '${project.version}'
api-version: 1.13
permissions:
  arcadia.heal:
    description: Allows the player to use the heal command (/arcadia heal)
    default: op
  arcadia.item:
    description: Allows the player to use the i command (/arcadia i <item>)
    default: op
  arcadia.enchant:
    description: Allows the player to use the enchant command (/arcadia enchant)
    default: op
  arcadia.summon:
    description: Allows the player to use the summon command (/arcadia summon)
    default: op
  arcadia.spawn:
    description: Allows the player to use the spawn command (/arcadia spawn)
    default: op
  arcadia.loot:
    description: Allows the player to use the loot command (/arcadia loot)
    default: op
  arcadia.debug:
    description: Allows the player to use the debug command (/arcadia debug)
    default: op
  arcadia.gui:
    description: Allows the player to use the opengui command (/arcadia opengui)
    default: op
  arcadia.recipe:
    description: Allows the player to view any recipe (/arcadia viewrecipe)
    default: true
  arcadia.upgrade:
    description: Allows the player to view any upgrade (/arcadia viewupgrade)
    default: true
  arcadia.lobby:
    description: Allows the player to go to the lobby (/arcadia lobby)
    default: true
  arcadia.dungeon:
    description: Allows the player to manage dungeons (/arcadia dungeons)
    default: op
  arcadia.data:
    description: Allows the player to manage player data (/arcadia playerdata)
    default: op
  arcadia.npc:
    description: Allows the player to manage npcs (/arcadia npc)
    default: op
  arcadia.effect:
    description: Allows the player to manage entity effects (/arcadia effect)
    default: op
  arcadia.command:
    description: Allows the player to use the default arcadia command (/arcadia)
    default: true

  arcadia.player:
    description: Allows the player to use all default player commands
    default: true
    children:
      arcadia.recipe: true
      arcadia.upgrade: true
      arcadia.command: true
      arcadia.lobby: true

  arcadia.admin:
    description: Allows the player to use all admin commands
    default: op
    children:
      arcadia.player: true
      arcadia.heal: true
      arcadia.item: true
      arcadia.summon: true
      arcadia.spawn: true
      arcadia.gui: true
      arcadia.debug: true
      arcadia.loot: true
      arcadia.enchant: true
      arcadia.dungeons: true
      arcadia.data: true
      arcadia.npc: true
